# Generated by Django 2.2.2 on 2019-06-21 19:40

import composite_pk.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('x', models.IntegerField()),
                ('y', models.CharField(max_length=8)),
                ('primary_key', composite_pk.fields.CompositePrimaryKey('x', 'y', primary_key=True, serialize=False)),
            ],
        ),
    ]
