# Generated by Django 2.2.2 on 2019-07-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test00_basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
